from pathlib import Path

path = Path("HintFilmIzle/src/main/kotlin/com/nikyokki/HintFilmIzlePlugin.kt")
s = path.read_text(encoding="utf-8-sig")

replacements = {
    'val apiBase = "https://kinescope.io/api/v1/embed/$id"': 'val apiBase = "https://${parsed.host}/api/v1/embed/$id"',
    'val kinescopeIframe = "https://kinescope.io/embed/$id"': 'val kinescopeIframe = kine',
}
for old, new in replacements.items():
    if old not in s:
        raise SystemExit(f"Kinescope target not found: {old}")
    s = s.replace(old, new, 1)

# The actual HintFilmIzle player URL is a signed Kinescope CDN embed URL.
# Fetching that URL exposes the signed /api/v1/embed request generated by Kinescope.
old = '''            val embedBody = runCatching {
                app.get(kinescopeIframe, referer = parent, headers = headers()).text
            }.getOrNull().orEmpty()
'''
new = '''            val embedBody = runCatching {
                app.get(kinescopeIframe, referer = parent, headers = headers()).text
            }.getOrNull().orEmpty()
            Log.d("HintFilmIzle", "KINESCOPE_EMBED_HOST=${parsed.host}")
            Log.d("HintFilmIzle", "KINESCOPE_EMBED_BODY_LEN=${embedBody.length}")
'''
if old not in s:
    raise SystemExit("Kinescope embed fetch block not found")
s = s.replace(old, new, 1)

# Do not fabricate an unsigned kinescope.io API URL when the CDN embed did not expose a signed API.
old = 'val candidates = listOfNotNull(signedApi, "$apiBase?$params").distinct()'
new = 'val candidates = listOfNotNull(signedApi).distinct()'
if old not in s:
    raise SystemExit("Kinescope candidates block not found")
s = s.replace(old, new, 1)

path.write_text(s, encoding="utf-8")
print("HintFilmIzle signed Kinescope CDN fix applied")
