package com.nikyokki

import com.lagradost.cloudstream3.SubtitleFile
import com.lagradost.cloudstream3.utils.ExtractorApi
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.ExtractorLinkType
import com.lagradost.cloudstream3.utils.Qualities
import com.lagradost.cloudstream3.utils.newExtractorLink
import com.lagradost.cloudstream3.app
import org.jsoup.Jsoup

/**
 * Extracts the HLS master playlist generated by Vidmixi's bePlayer.
 * The embed page exposes the already-initialized player configuration,
 * whose source is a /list/... HLS master playlist.
 */
class VidmixiExtractor : ExtractorApi() {
    override val name = "Vidmixi"
    override val mainUrl = "https://vidmixi.com"
    override val requiresReferer = true

    override suspend fun getUrl(
        url: String,
        referer: String?,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ) {
        val response = app.get(
            url,
            referer = referer ?: mainUrl,
            headers = mapOf("User-Agent" to USER_AGENT)
        )

        val document = response.document
        val html = response.text

        // bePlayer initializes JW Player with: file: "https://vidmixi.com/list/..."
        val m3u8 = Regex(
            "(?:file|source|src)\\s*[:=]\\s*[\\\"'](https?://(?:www\\.)?vidmixi\\.com/list/[^\\\"']+)"
        ).find(html)?.groupValues?.getOrNull(1)
            ?: Regex("https?://(?:www\\.)?vidmixi\\.com/list/[^\\\"'\\s<>]+")
                .find(html)?.value

        if (m3u8 != null) {
            callback.invoke(
                newExtractorLink(
                    source = name,
                    name = name,
                    url = m3u8,
                    type = ExtractorLinkType.M3U8
                ) {
                    this.referer = url
                    this.quality = Qualities.Unknown.value
                }
            )
        }

        // Vidmixi exposes subtitle tracks in the player configuration.
        val subtitleUrls = Regex(
            "https?://(?:www\\.)?vidmixi\\.com/[^\\\"'\\s<>]+\\.vtt(?:\\?[^\\\"'\\s<>]*)?"
        ).findAll(html).map { it.value }.distinct()

        subtitleUrls.forEach { subtitleUrl ->
            val label = when {
                subtitleUrl.contains("Turk", ignoreCase = true) || subtitleUrl.contains("turk", ignoreCase = true) -> "Türkçe"
                subtitleUrl.contains("English", ignoreCase = true) || subtitleUrl.contains("eng", ignoreCase = true) -> "English"
                else -> "Altyazı"
            }
            subtitleCallback.invoke(SubtitleFile(label, subtitleUrl))
        }
    }

    private companion object {
        const val USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
    }
}
